Repository ghostty-org/discord-bot, pull requests merged in 2025-05, with the labels that each got.

#221 github-integration: prefer html_url over url for user models
  app/components/github_integration/models.py
Labels: area: github-integration

#222 Improve moved message sticker embeds
  app/utils/webhooks.py
Labels: area: message-moving

#223 Update pyright commands to type-check `tests` too
  .github/workflows/ci.yml
  README.md
Labels: internal

#225 Disable mentions in the ghost ping note
  app/components/move_message.py
Labels: area: message-moving

#231 github-integration: special-case some languages for code links
  app/components/github_integration/code_links.py
Labels: area: github-integration

#224 Make MessageData a subclass of discord.Message
  app/utils/__init__.py
  app/utils/message_data.py
  app/utils/webhooks.py
  pyproject.toml
  uv.lock
Labels: internal

#230 Add a hint about things to update when changing `.env.example`
  .env.example
Labels: internal

#226 `_format_subtext` rewrite
  app/utils/webhooks.py
Labels: internal, area: message-moving

#232 Handle Nitro emojis in forwards
  app/utils/webhooks.py
Labels: area: message-moving

#227 Remove reactions from moved forwards
  app/utils/webhooks.py
Labels: area: message-moving

#237 More mention aliases
  app/components/github_integration/mentions/resolution.py
Labels: area: github-integration
