Repository ghostty-org/discord-bot, pull requests merged in 2025-04, with the labels that each got.

#196 Name linked entities again
  README.md
  app/components/entity_mentions/fmt.py
  app/components/entity_mentions/resolution.py
Labels: area: entity-mentions

#201 Avoid reacting with entity mentions on an entity comment link
  app/components/entity_mentions/resolution.py
Labels: area: entity-mentions

#193 Lock old posts to discourage necroposting
  app/components/autoclose.py
  app/components/lock_old_posts.py
  app/core.py
  app/utils/__init__.py
Labels: area: help-posts

#197 Cover closing and locking #help posts in the README
  README.md
Labels: documentation

#204 Don't die on very early status requests
  app/components/status.py
Labels: bug, internal

#205 Store the lock threshold in a variable
  app/components/lock_old_posts.py
Labels: internal

#198 Add support for XKCD mentions
  README.md
  app/components/entity_mentions/resolution.py
  app/components/xkcd_mentions.py
  app/core.py
  app/utils/hooks.py
Labels: new-feature, area: entity-mentions

#207 Add hyperlinks to all relevant parts of the code links message
  app/components/entity_mentions/code_links.py
Labels: area: github-integration

#209 Handle character ranges in code links
  app/components/entity_mentions/code_links.py
Labels: area: github-integration

#210 Handle www.github.com
  app/components/entity_mentions/code_links.py
  app/components/entity_mentions/comments/fetching.py
  app/components/entity_mentions/resolution.py
Labels: area: github-integration

#211 components: rename entity_mentions to github_integration
  app/components/__init__.py
  app/components/close_help_post.py
  app/components/github_integration/__init__.py
  app/components/github_integration/code_links.py
  app/components/github_integration/comments/__init__.py
  app/components/github_integration/comments/fetching.py
  app/components/github_integration/comments/integration.py
  app/components/github_integration/mentions/__init__.py
  app/components/github_integration/mentions/cache.py
  app/components/github_integration/mentions/discussions.py
  app/components/github_integration/mentions/fmt.py
  app/components/github_integration/mentions/integration.py
  app/components/github_integration/mentions/resolution.py
  app/components/github_integration/models.py
  app/core.py
  tests/test_close_help_post.py
Labels: internal, area: github-integration

#212 misc: various improvements
  app/components/autoclose.py
  app/components/close_help_post.py
  app/components/github_integration/comments/fetching.py
  app/components/github_integration/mentions/fmt.py
  app/components/github_integration/mentions/integration.py
  app/components/github_integration/models.py
  app/components/message_filter.py
  app/components/move_message.py
  app/components/status.py
  app/components/xkcd_mentions.py
  app/core.py
  app/utils/hooks.py
  tests/utils/kitposer.py
Labels: internal

#208 Differentiate between branches and revisions
  app/components/github_integration/code_links.py
Labels: area: github-integration

#213 github-integration: split discussions module
  app/components/github_integration/comments/discussions.py
  app/components/github_integration/comments/fetching.py
  app/components/github_integration/mentions/discussions.py
Labels: internal, area: github-integration

#202 Handle Nitro reactions in moved messages
  app/utils/message_data.py
  app/utils/webhooks.py
Labels: area: message-moving

#214 zig-codeblocks: bump to 0.3.0
  app/components/zig_codeblocks.py
  pyproject.toml
  uv.lock
Labels: internal

#215 Limit the length of #help post titles
  app/components/move_message.py
Labels: area: help-posts

#216 deps: bump githubkit to 0.12.11
  pyproject.toml
  uv.lock
Labels: bug, area: github-integration

#217 zig-codeblocks: bump to 0.3.1
  pyproject.toml
  uv.lock
Labels: internal

#218 Prefer `typing.Self`
  app/components/docs.py
  app/components/move_message.py
  app/components/zig_codeblocks.py
  app/utils/__init__.py
Labels: internal
