Repository ghostty-org/discord-bot, pull requests merged in 2025-02, with the labels that each got.

#143 Use a Discord timestamp for entity mention dates
  app/components/entity_mentions/fmt.py
Labels: area: entity-mentions

#142 feat: allow mentioning entities from any GitHub repo
  app/components/entity_mentions/__init__.py
  app/components/entity_mentions/cache.py
  app/components/entity_mentions/fmt.py
  app/components/entity_mentions/resolution.py
Labels: area: entity-mentions

#144 feat: rework `/close` command
  .env.example
  app/components/autoclose.py
  app/components/close_help_post.py
  app/components/docs.py
Labels: area: help-posts

#161 build: drop nix, migrate to uv
  .envrc
  .github/workflows/ruff.yml
  .python-version
  LICENSE
  README.md
  app/components/entity_mentions/cache.py
  app/components/entity_mentions/fmt.py
  app/components/move_message.py
  app/config.py
  flake.lock
  flake.nix
  nix/devshell.nix
  nix/overlay.nix
  nix/package.nix
  nix/python-app.nix
  poetry.lock
  pyproject.toml
  uv.lock
Labels: internal

#145 feat: add Zig syntax highlighting
  app/components/__init__.py
  app/components/entity_mentions/__init__.py
  app/components/entity_mentions/integration.py
  app/components/zig_codeblocks.py
  app/core.py
  app/utils.py
  pyproject.toml
  uv.lock
Labels: new-feature

#154 improve utils; fix zig-codeblocks message unlinking
  app/components/docs.py
  app/components/entity_mentions/integration.py
  app/components/zig_codeblocks.py
  app/core.py
  app/utils.py
  app/utils/__init__.py
  app/utils/message_data.py
  app/utils/webhooks.py
Labels: bug, internal

#163 Handle long help post titles gracefully
  app/components/close_help_post.py
Labels: area: help-posts

#168 feat(docs): add close command section in `README.md`
  README.md
Labels: documentation

#169 feat: add a bot status command
  app/components/__init__.py
  app/components/autoclose.py
  app/components/docs.py
  app/components/entity_mentions/fmt.py
  app/components/status.py
  app/core.py
  app/utils/__init__.py
Labels: internal
