Repository ghostty-org/discord-bot, pull requests merged in 2025-03, with the labels that each got.

#166 Move nitro emojis
  app/components/entity_mentions/fmt.py
  app/utils/__init__.py
  app/utils/webhooks.py
Labels: area: message-moving

#170 refactor(entity-mentions): use pydantic models for entities
  app/components/entity_mentions/cache.py
  app/components/entity_mentions/discussions.py
  app/components/entity_mentions/fmt.py
  app/components/entity_mentions/integration.py
  app/components/entity_mentions/models.py
  app/components/entity_mentions/resolution.py
  app/utils/__init__.py
  pyproject.toml
  uv.lock
Labels: internal, area: entity-mentions

#167 Move stickers
  app/utils/webhooks.py
  pyproject.toml
  uv.lock
Labels: area: message-moving

#164 Sanitize markdown in GitHub entity titles
  app/components/entity_mentions/fmt.py
  app/components/entity_mentions/integration.py
  app/utils/__init__.py
Labels: area: entity-mentions

#177 Add Pyright
  .github/workflows/ci.yml
  README.md
  app/components/close_help_post.py
  app/components/docs.py
  app/components/entity_mentions/integration.py
  app/components/message_filter.py
  app/components/move_message.py
  app/components/zig_codeblocks.py
  pyproject.toml
  uv.lock
Labels: internal

#176 feat: display entity comments
  app/components/entity_mentions/__init__.py
  app/components/entity_mentions/comments/__init__.py
  app/components/entity_mentions/comments/fetching.py
  app/components/entity_mentions/comments/integration.py
  app/components/entity_mentions/discussions.py
  app/components/entity_mentions/fmt.py
  app/components/entity_mentions/integration.py
  app/components/entity_mentions/models.py
  app/core.py
  app/utils/__init__.py
Labels: new-feature, area: entity-mentions

#181 Improve the error message when the bot guild name does not contain `ghostty`
  app/utils/webhooks.py
Labels: internal

#165 Ignore polls that have ended
  app/utils/webhooks.py
Labels: area: message-moving

#182 feat: implement linking code snippets
  app/components/entity_mentions/__init__.py
  app/components/entity_mentions/code_links.py
  app/core.py
Labels: new-feature

#184 refactor: abstract away update hooks
  app/components/entity_mentions/__init__.py
  app/components/entity_mentions/code_links.py
  app/components/entity_mentions/comments/__init__.py
  app/components/entity_mentions/comments/integration.py
  app/components/entity_mentions/integration.py
  app/components/zig_codeblocks.py
  app/core.py
  app/utils/__init__.py
  app/utils/hooks.py
Labels: internal, area: entity-mentions

#186 Include the moved message's timestamp
  app/utils/__init__.py
  app/utils/message_data.py
  app/utils/webhooks.py
Labels: area: message-moving

#188 test: lay groundwork for test suite
  .github/workflows/ci.yml
  README.md
  app/components/close_help_post.py
  app/components/docs.py
  app/core.py
  pyproject.toml
  tests/__init__.py
  tests/conftest.py
  tests/fixtures/__init__.py
  tests/fixtures/config.py
  tests/test_close_help_post.py
  tests/utils/__init__.py
  tests/utils/kitposer.py
  uv.lock
Labels: internal

#192 Small changes to TTRCache
  app/components/entity_mentions/cache.py
  app/components/entity_mentions/code_links.py
  app/components/entity_mentions/comments/fetching.py
  app/components/entity_mentions/resolution.py
  app/utils/__init__.py
  app/utils/cache.py
Labels: internal

#189 Move replies, forwards and interactions, and disallow moving system messages
  app/components/move_message.py
  app/utils/__init__.py
  app/utils/webhooks.py
Labels: area: message-moving
