Repository ghostty-org/discord-bot, pull requests merged in 2025-01, with the labels that each got.

#99 Escape underscores in username when ghost-pinging
  app/components/move_message.py
Labels: improvement

#100 fix: skip page autocomplete if section wasn't filled out
  app/components/docs.py
Labels: bug, improvement

#105 fix: ignore unknown entity mentions
  app/components/entity_mentions.py
Labels: bug

#102 feat: improve `/docs` command
  app/components/docs.py
Labels: feature, improvement

#110 feat: autoclose `#help` posts after 24h
  .env.example
  app/components/__init__.py
  app/components/autoclose.py
  app/config.py
  app/core.py
Labels: feature

#107 feat: better type narrowing
  app/components/message_filter.py
  app/components/move_message.py
  app/utils.py
Labels: internal

#115 feat: streamline move message view
  app/components/move_message.py
Labels: improvement

#114 docs: add project documentation
  README.md
Labels: documentation

#104 build: update python version to 3.12
  README.md
  flake.lock
  poetry.lock
  pyproject.toml
Labels: internal

#121 feat: revamp entity mentions
  app/components/entity_mentions.py
  app/core.py
Labels: feature

#122 fix: attach message content if too long when moving
  app/utils.py
Labels: improvement

#124 feat: send back the message content when filtered
  README.md
  app/components/message_filter.py
  app/utils.py
Labels: improvement

#125 fix: correctly handle force-deleted mentions
  app/components/entity_mentions.py
  app/core.py
Labels: bug, improvement

#126 Allow moderators to delete any entity mention
  app/components/entity_mentions.py
Labels: improvement

#128 feat: add `/accept-invite`
  .env.example
  app/components/__init__.py
  app/components/accept_invite.py
  app/config.py
Labels: feature

#127 refactor: make `entity_mentions` its own package
  app/components/__init__.py
  app/components/accept_invite.py
  app/components/entity_mentions.py
  app/components/entity_mentions/__init__.py
  app/components/entity_mentions/cache.py
  app/components/entity_mentions/discussions.py
  app/components/entity_mentions/fmt.py
  app/components/entity_mentions/integration.py
  app/components/move_message.py
  app/core.py
Labels: internal

#123 feat: implement `/close` command
  .env.example
  app/components/__init__.py
  app/components/close_help_post.py
  app/components/entity_mentions/__init__.py
  app/config.py
Labels: feature

#129 build: replace `pygithub` with `githubkit`
  app/components/docs.py
  app/components/entity_mentions/__init__.py
  app/components/entity_mentions/cache.py
  app/components/entity_mentions/discussions.py
  app/components/entity_mentions/fmt.py
  app/setup.py
  nix/python-app.nix
  poetry.lock
  pyproject.toml
Labels: internal, improvement

#132 perf: improve entity fetching flow
  app/components/entity_mentions/cache.py
  app/components/entity_mentions/discussions.py
  app/components/entity_mentions/fmt.py
  app/components/entity_mentions/integration.py
Labels: internal, improvement

#133 refactor: add a util for packing long messages into attachments
  app/components/message_filter.py
  app/utils.py
Labels: internal

#135 fix: gracefully handle fetch fails
  app/components/entity_mentions/fmt.py
Labels: bug
